### ISSUE TITLE
UnboundLocalError for local variable psf

### ISSUE THREAD

**Issue by dkvieira** [TimothyADavis/KinMSpy#12]
Hello!

I recently encountered a bug while using KinMSpy. It has to do with the way the variable "psf" is defined in the function "model_cube".

"psf" is a local variable in "model_cube" defined for the first time inside an if statement (line 1051-1053). 

The problem is that if the if statement is false (which happens if one sets CleanOut=True), "psf" does not get defined before it is used as an argument for "normalise_cube" on line 1071.

This leads to the error in python3: 

"UnboundLocalError: local variable 'psf' referenced before assignment"

A quick fix would be to initialise "psf" to something inside "model_cube" before the if statement.

**Comment by TimothyADavis** [comment]
Many thanks @dkvieira ! Not sure how that got through the testing net - should be fixed now.
