### ISSUE TITLE
Same seed used for 2 different RNGs

### ISSUE THREAD

**Issue by NanoExplorer** [TimothyADavis/KinMSpy#14]
Hello, 
    I noticed that `seed[3]` is used to initialize two different RNGs, both the z-height generator and the velocity dispersion generator, so if people wanted to generate thick disks there could be correlation between the height of a cloud and its random velocity. `seed[2]` was never used, so one could easily change one of these to use that instead.

https://github.com/TimothyADavis/KinMSpy/blob/5b070429393dd8627aa45396d3485758f814c65d/kinms/KinMS.py#L522
https://github.com/TimothyADavis/KinMSpy/blob/5b070429393dd8627aa45396d3485758f814c65d/kinms/KinMS.py#L579

... edit: It looks like the seed array is re-created before the second use, which means this might not be an issue. Though when it is recreated, it is recreated as an integer between 0 and 99, so there's a small (1/1000?) chance you could end up with the same seed between the first use of `seed[0]` and the final use of `seed[3]`, because `seed[0]` will be a random integer between 0 and 999 and this use of `seed[3]` will be an integer between 0 and 99

The seed array is created in `kinms_sampleFromArbDist_oneSided`
https://github.com/TimothyADavis/KinMSpy/blob/5b070429393dd8627aa45396d3485758f814c65d/kinms/KinMS.py#L494

and re-created in kinms_create_velField_oneSided
https://github.com/TimothyADavis/KinMSpy/blob/5b070429393dd8627aa45396d3485758f814c65d/kinms/KinMS.py#L572

I have a proposal for a fix. I can implement it and send you a pull request if you'd like. Just let me know!

**Comment by TimothyADavis** [comment]
Thanks for spotting this- I have a fix implemented now in 2.1.1, let me know if you spot any issues!
