### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by yangcht** [TimothyADavis/KinMSpy#2]
error: 

> SyntaxError: Non-ASCII character '\xc4' in file KinMS.py on line 162, but no encoding declared;

Please consider adding encoding declare at the beginning

**Comment by TimothyADavis** [comment]
Many thanks for the heads up- as someone moving slowly from IDL to python this isn't something I had considered before!

I think this should be fixed now- please let me know, as I haven't been able to reproduce the error myself with my python install.

**Comment by yangcht** [comment]
Many thanks!
