### ISSUE TITLE
KinMS fails to produce a reasonable model with nonzero phase center

### ISSUE THREAD

**Issue by NanoExplorer** [TimothyADavis/KinMSpy#5]
Hello, I recently started using KinMS to try to generate a model for a galaxy I've been observing. However, the model parameters I was getting out of the fitting software weren't reasonable. When I tried to generate an image of the KinMS model my fitting software was producing using the plotting method in the KinMS_testsuite, it looked really weird. The velocity profile and integrated line emission were not symmetrical, which seems unphysical to me for a single rotating disk. 

After doing some digging, and trying to produce the least-complicated KinMS call that reproduces my issue, I came up with the following:

The model looks fine unless either of `phaseCen` or `vPhaseCen` is nonzero. As far as I can tell, the `phaseCen` and `vPhaseCen` variables control the position of the center of the model disk inside the cube, so I would not expect changing these variables to change the line profile integrated over the whole cube (unless I moved the disk outside of the image cube). However, changing them can cause the line profile to change, either adding a cusp-like feature in the center or a large amount of asymmetry.

Another important point to mention is that one of my colleagues can run this code with no issues. I think that he might be using different versions of certain python packages. I've tried two combinations, one on my laptop and one on my group's workstation. My laptop has Anaconda 3: Python 3.7.1, Astropy 3.1, Numpy 1.15.4, and Scipy 1.1.0, and the workstation has Anaconda 2: Python 2.7.16, Astropy 2.0.9, Numpy 1.16.2, and Scipy 1.2.1. Both of my installations were cloned from this KinMS Github page in the past week. I do not know what my colleague's installation looks like or when he last updated KinMS. My two different installations give the same results.

I have uploaded a sample test script here: https://gist.github.com/NanoExplorer/b8d2e1f4fab2598fece6e8c52efd62fb 

And here are my results for various parameters. First is the expected result with `phasecen` and `vphasecen = [0,0]`.
![0xycen](https://user-images.githubusercontent.com/4166159/57398402-e443db80-719c-11e9-8a34-a083708bf38a.png)
Then changing them to `phaseCen = vPhaseCen = [0.05,0]`
![0 05xcen](https://user-images.githubusercontent.com/4166159/57398449-fe7db980-719c-11e9-9190-dd9174f49f5f.png)
Then, finally, changing them to `phaseCen = vPhaseCen = [0,0.05]`
![0 05ycen](https://user-images.githubusercontent.com/4166159/57398477-0d646c00-719d-11e9-925e-af85e374439e.png)

Thanks for taking the time to look at this! Let me know if you can find something I'm doing wrong or have an idea for how to fix this.

**Comment by NanoExplorer** [comment]
I just tried some other things. Is the problem that I was modifying vPhaseCen, which should be left at zero? I.e., will the center of the velocity field be the same as the center of the surface brightness profile only if vPhaseCen is zero?

**Comment by NanoExplorer** [comment]
In Commit b03e162 a bug was fixed regarding the offset between kinematic and morphological centers. My colleague had been using the older version of the code without this fix, and his code contained a workaround for this bug, When the bug was fixed, I needed to remove the workaround.

**Comment by TimothyADavis** [comment]
Hi @NanoExplorer - thanks for raising this- I came to try and fix this issue today and found that its already sorted! Glad it all got cleared up, and great that you find the code useful!
